INSERT INTO curator VALUES(1, 4);
INSERT INTO curator VALUES(2, 8);
INSERT INTO curator VALUES(3, 3);
INSERT INTO curator VALUES(4, 10);
INSERT INTO curator VALUES(5, 2);
INSERT INTO curator VALUES(6, 11);
INSERT INTO curator VALUES(7, 7);